### PR TITLE
Preparing release 1.0.0

### PR DESCRIPTION
**Pull request by Natim**
r? @glasserc 

- [x] Add some documentation in the README.

### CODE REVIEW

**Comment by glasserc** [comment]
`listeners/redis.py` seems not to have made it over (https://github.com/Kinto/kinto/pull/753/files#diff-2bfaf581fb7c238a1f1e98f50687bc98). Is this intentional?

**Comment by Natim** [comment]
>  Is this intentional?

At first I moved it here but then the kinto coverage for the listener was broken because the redis listener is the only core listener.

I can make it so that the redis listener doesn't depends on kinto-redis if you want.

**Comment by glasserc** [comment]
r+. Thanks for taking the initiative on this!

**Comment by Natim** [comment]
> Thanks for taking the initiative on this!

You are welcome :)

**Pull request merged**
